// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
  defaultTemplateId: 'default',
  defaultAltTemplateId: 'defaultAlt',
  templates: {
    default: '<div class="chat-message"><p><i class="bi bi-envelope-open-fill"></i>&nbsp;&nbsp;<b>Chat</b></p><div class="chat-message-body"><strong>{0}:</strong> {1}</div></div>',
    defaultAlt: '{0}',
    print: '<pre>{0}</pre>',
    'example:important': '<h1>^2{0}</h1>'
  },
  fadeTimeout: 4000,
  suggestionLimit: 5,
  style: {
    background: 'transparent'
  }
};
